runtime: python310
entrypoint: gunicorn --workers 1 --threads 8 --timeout 0 app:app

env_variables:
  NLTK_DATA: "/tmp"
  FLASK_ENV: "production"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

instance_class: F2

automatic_scaling:
  max_instances: 2
  min_instances: 1
  min_idle_instances: 1
